// <auto-generated />
using KunstWerk.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KunstWerk.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KunstWerk.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Nancy",
                            LastName = "Bailleux",
                            PlaceOfBirth = "Antwerpen",
                            YearOfBirth = "1964"
                        });
                });

            modelBuilder.Entity("KunstWerk.Models.Tech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Techniek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Techniek = "Acryl"
                        },
                        new
                        {
                            Id = 2,
                            Techniek = "Aquarel"
                        },
                        new
                        {
                            Id = 3,
                            Techniek = "Aquarel & fineliner"
                        },
                        new
                        {
                            Id = 4,
                            Techniek = "Aquatint"
                        },
                        new
                        {
                            Id = 5,
                            Techniek = "Bister"
                        },
                        new
                        {
                            Id = 6,
                            Techniek = "Balpen & markers"
                        },
                        new
                        {
                            Id = 7,
                            Techniek = "Cement"
                        },
                        new
                        {
                            Id = 8,
                            Techniek = "Ets"
                        },
                        new
                        {
                            Id = 9,
                            Techniek = "Ets, droge naald"
                        },
                        new
                        {
                            Id = 10,
                            Techniek = "Gemengde techniek"
                        },
                        new
                        {
                            Id = 11,
                            Techniek = "Gouache"
                        },
                        new
                        {
                            Id = 12,
                            Techniek = "Houtsnede"
                        },
                        new
                        {
                            Id = 13,
                            Techniek = "Keramiek"
                        },
                        new
                        {
                            Id = 14,
                            Techniek = "Klei"
                        },
                        new
                        {
                            Id = 15,
                            Techniek = "Kleurpotlood"
                        },
                        new
                        {
                            Id = 16,
                            Techniek = "Linosnede"
                        },
                        new
                        {
                            Id = 17,
                            Techniek = "Nagellak"
                        },
                        new
                        {
                            Id = 18,
                            Techniek = "Litho"
                        },
                        new
                        {
                            Id = 19,
                            Techniek = "Offset druk"
                        },
                        new
                        {
                            Id = 20,
                            Techniek = "Olieverf"
                        },
                        new
                        {
                            Id = 21,
                            Techniek = "Oostindische inkt"
                        },
                        new
                        {
                            Id = 22,
                            Techniek = "Opgehoogde zeefdruk"
                        },
                        new
                        {
                            Id = 23,
                            Techniek = "PC grafiek"
                        },
                        new
                        {
                            Id = 24,
                            Techniek = "Print op doek"
                        },
                        new
                        {
                            Id = 25,
                            Techniek = "Print op fotopapier"
                        },
                        new
                        {
                            Id = 26,
                            Techniek = "Resin"
                        },
                        new
                        {
                            Id = 27,
                            Techniek = "Zeefdruk"
                        });
                });

            modelBuilder.Entity("KunstWerk.Web.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("TechId");

                    b.ToTable("Artwork");
                });

            modelBuilder.Entity("KunstWerk.Web.Models.Artwork", b =>
                {
                    b.HasOne("KunstWerk.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KunstWerk.Models.Tech", "Tech")
                        .WithMany()
                        .HasForeignKey("TechId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Tech");
                });
#pragma warning restore 612, 618
        }
    }
}
